const mongoose = require("mongoose");

const productSchema = new mongoose.Schema({
    ID: { type: Number, default: null },
    Type: { type: String, default: "" },
    SKU: { type: String, default: "" },
    GTIN_UPC_EAN_or_ISBN: { type: String, default: "" },
    Name: { type: String, default: "" },
    Published: { type: Number, default: null },
    Is_featured: { type: Number, default: null },
    Visibility_in_catalog: { type: String, default: "" },
    Short_description: { type: String, default: "" },
    Description: { type: String, default: "" },
    Date_sale_price_starts: { type: String, default: "" },
    Date_sale_price_ends: { type: String, default: "" },
    Tax_status: { type: String, default: "" },
    Tax_class: { type: String, default: "" },
    In_stock: { type: Number, default: null },
    Stock: { type: Number, default: null },
    Low_stock_amount: { type: Number, default: null },
    Backorders_allowed: { type: String, default: "" },
    Sold_individually: { type: String, default: "" },
    Weight_kg: { type: Number, default: null },
    Length_cm: { type: Number, default: null },
    Width_cm: { type: Number, default: null },
    Height_cm: { type: Number, default: null },
    Allow_customer_reviews: { type: String, default: "" },
    Purchase_note: { type: String, default: "" },
    Sale_price: { type: String, default: "" },
    Regular_price: { type: String, default: "" },
    Categories: { type: String, default: "" },
    Tags: { type: String, default: "" },
    Shipping_class: { type: String, default: "" },
    Images: { type: String, default: "" },
    Download_limit: { type: Number, default: null },
    Download_expiry_days: { type: Number, default: null },
    Parent: { type: String, default: "" },
    Grouped_products: { type: String, default: "" },
    Upsells: { type: String, default: "" },
    Cross_sells: { type: String, default: "" },
    External_URL: { type: String, default: "" },
    Button_text: { type: String, default: "" },
    Position: { type: Number, default: null },
    Brands: { type: String, default: "" },
}, {
    timestamps: true,
});

module.exports = mongoose.model("ProductMaster", productSchema);
